### ISSUE TITLE
Stabilize and catalog all document formats (chapter, book-chapter, book-chapter-section, etc.)

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_api#12]
In order to sync data from the text server to the Meteor application's database, we need to better define the different document formats. What makes a document "chapter" v. "book-chapter", etc.?

It only really matters for the API to understand how many levels of nested content there are.  We can build it to be flexible if each level of nested content above the actual string of text (book, chapter, poem, etc.) has a similar structure.

**Comment by kylepjohnson** [comment]
Is this an issue you need my feedback on? If I understand right, you're saying that what really matters is depth of nesting?

**Comment by lukehollis** [comment]
Yes, that's correct--I think we just need to know the depth of nesting for the first round of updates. 

We should get somewhat of a list together as we build so the text-sync script knows what to do with them.  So far I see chapter, book-chapter, book-line, and poem-line. Is there anything else? 

At some point it would maybe make sense to infer genre from these as well.

**Comment by kylepjohnson** [comment]
Types of chunking of classical works (off the top of my head): chapter, chapter-section book-chapter, book-chapter-section, book-line, and poem-line, fragment, fragment-line, line (as in plays).

I assume that these will need slightly different fontend templates for displaying their contents. If discerning depth of nesting, a cheap and easy way might be to infer this from the "meta" tag, ie, "fragement-line" has a depth of 2, "lines" 1, "book-chapter-section" 3.

> At some point it would maybe make sense to infer genre from these as well.
> If by genre here you mean, say, dramatic play vs. prose text vs. epic poetry – then, yes, that may be inferred. But I think it's obvious that we can't parse historiography from philosphy, or lyric from odes.

**Comment by lukehollis** [comment]
Okay, great--this is super helpful, thanks. I'll add these to the wiki page, and if we run into more ambiguities in the future can reopen this issue.  Seems to be ready to be closed for now.
