### ISSUE TITLE
Renaming API name gives error with gunicorn command

### ISSUE THREAD

**Issue by manu-chroma** [cltk/cltk_api#13]
After setting up `cltk_api` I was able to run the API through `python api.py` command but not through `gunicorn -w 4 -b 0.0.0.0:5000 api:app` (Error in the screenshot)
I changed to it's old name `api_json.py` and run the command `gunicorn -w 4 -b 0.0.0.0:5000 api_json:app` and it worked. 
I think the already present `api/` folder in the same directory creates conflict when the `gunicorn` command is run and API is named `api.py` 
Can someone else please verify the same error on their system ?
P.S: Name of the API was updated 2 commits back. https://github.com/cltk/cltk_api/commit/2bcc0da43dabb27efab60c025b767b803e43eb05
Terminal Output: 
![image](https://cloud.githubusercontent.com/assets/12952080/13728760/3f48e25e-e948-11e5-817e-12ea982c7444.png)
`OS: Ubuntu 15.10 (64-bit)`

**Comment by kylepjohnson** [comment]
Hi, yes, this was a bug I introduced several commits ago. I will leave it to you to fix :)

**Comment by sameeriitkgp** [comment]
@manu-chroma Yeah!
I got the same error on my system.
Renaming the api.py file to api_json.py did it.

@kylepjohnson Shall I send the PR?
