### ISSUE TITLE
Add cltk_api to Travis CI build server

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltk_api#16]
To be done once #15 is at least minimally accomplished.

**Comment by kylepjohnson** [comment]
@modassir I'll get this ticket started then pass to you, if you're interested in learning about Travis CI.

**Comment by modassir** [comment]
Sure, will do it.

**Comment by kylepjohnson** [comment]
@modassir I have enabled the Tavis CI service for this repo:

https://travis-ci.org/cltk/cltk_api

You'll need to add a .travis.yaml [similar to the CLTK's](https://github.com/cltk/cltk/blob/master/.travis.yml). For this, install cltk, flask, etc with `pip install cltk`. I'll let you figure out the rest.

Should this ticket not interest you, let me know and we can find someone else. Thanks much.
