### ISSUE TITLE
Add route for accessing CLTK stemmer

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_api#20]
To get started with adding routes for accessing the CLTK core modules, an easy first step seems to be to add a route which we can send a GET request to with an input string of Latin words and receive a stemmed string of Latin words in response.  I'll take a look at adding this unless anyone else is interested in working on it.

**Comment by modassir** [comment]
@lukehollis I am interested.

**Comment by sameeriitkgp** [comment]
I would like to work on this too.

**Comment by lukehollis** [comment]
Hey @modassir and @SameerIITKGP thanks so much--I just created a new branch that we can work on together at https://github.com/cltk/cltk_api/tree/feature/expose_cltk_core

Since @modassir asked first, maybe we'll let him work on the stemmer (I was imagining including it here: https://github.com/cltk/cltk_api/tree/feature/expose_cltk_core/metadata/stem, but there are a lot of good options).  We'll need the same thing for the other functionality of the CLTK core package though. @SameerIITKGP would you be interested in doing the same for the tokenizers? We can create a new issue for this. Or any other core modules that you're interested in would be great to include here. At some point it makes sense if we have the main ones at least.

As @kylepjohnson mentioned, the routes that you expose the stemming and tokenizers may change in the future, but breaking ground on incorporating the CLTK core modules with the stemmer is the main thing to keep making progress here.

**Comment by Imran31** [comment]
Hi, I would like to work on routes for [NER](http://docs.cltk.org/en/latest/latin.html#named-entity-recognition) and [POS tagging](http://docs.cltk.org/en/latest/latin.html#pos-tagging).

Would it make sense to send my pull requests to `feature/expose_cltk_core`?

**Comment by lukehollis** [comment]
That sounds great--thanks! I'll open up some new issues for those.

**Comment by kylepjohnson** [comment]
Hey all, I love to see all the excitement to contribute on this. Please do have a go at it. The worst that can happen is that I will want to change the routing in the future, but that might not be for a while. Go for it!

**Comment by Imran31** [comment]
Thanks @lukehollis , could you assign me to the NER and POS issues too?

@kylepjohnson I too think the project may need some restructuring. For example, all the tests are in a single file right now, and the REST resources and helper functions for the CLTK core are placed together in `/metadata`. I think it'll be convenient to have an `api/` folder with a Python file for each resource and the helper functions it uses (eg `/api/stemmer.py`, `/api/lang.py`) and a Python file for the tests for each resource (eg. `/tests/stemmer.py`).

Additionally, the routes could be in a seperate `routes.py` that contains a list of tuples `routes = [ (StemmerAPI, '/stemmer', 'stemmer'), ...]`, one for each REST resource. We can then loop over this and call `add_resource(resourceClass, url, endpoint=endpoint)`.

This way it is easy to extend the API by adding a new resource to this list, and then adding the resource and test Python file to the `/api` and `/tests` folders.

I plan to discuss this in my proposal, but if you open an issue to brainstorm the API design I'll be glad to chime in.

**Comment by Imran31** [comment]
Another way of organizing it would be like `/api/corpus/views.py`, `/api/corpus/models.py` and  `/api/corpus/utils.py` for the views, models and helper functions.

This seems increasingly complex. But it may be simpler to direct future developers and say "Add  helper functions to `utils.py`, add database stuff to `models.py`, ...".

**Comment by kylepjohnson** [comment]
Before talking folder/code structure, it would be helpful for me you'd start with URI design, then we work backwards. Some of CLTK core's code is nuanced, so you'll need to know some about it before proposing the API's code.

**Comment by modassir** [comment]
@kylepjohnson sure, I think one the method is to list down all the CLTK core's methods which needs to be implemented by the API. Then we can use any of the url scheme which suits us and gives proper meaning. 
https://github.com/cltk/cltk_api/issues/28#issuecomment-198932765  is a good approach.
