### ISSUE TITLE
Add "source" field to JSON

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltk_api#33]
To our ingested JSON documents, add "source" and "license" to the text output.

**Comment by lukehollis** [comment]
@kylepjohnson how do the source and sourceLink look in the updated JSON data format specs? https://github.com/cltk/cltk_api/wiki/JSON-data-format-specifications

**Comment by kylepjohnson** [comment]
I like it fine : )

**Comment by lukehollis** [comment]
Deal :) the documents in the cltk_json dirs for the text corpora so far have source and sourceLink--wished I'd remembered the License field also earlier. Closing this issue for now unless you'd like an additional License field as well.
