### ISSUE TITLE
Converting TLG texts with TLGU issue

### ISSUE THREAD

**Issue by m-ramesh** [cltk/cltk_api#7]
I have an issue trying to convert the TLG texts with TLGU. I use the code exactly as it is given in the instruction:

In [1]: from cltk.corpus.greek.tlgu import TLGU

In [2]: t = TLGU()

In [3]: t.convert_corpus(corpus='tlg')

I use Python 3.4.3 on Cygwin. When I enter [3], it does not do anything except start a newline waiting for me to enter another command. I checked and there is no file output.

By the way I cannot find PHI7 in my CLTK folders either.

**Comment by kylepjohnson** [comment]
Hi Ramesh, thanks for posting this. A few things.

1) Issues for the core software is at: https://github.com/cltk/cltk/issues. This repo is for a new web api.

2) Our software is not supported on Windows. It is tested on Ubuntu and Mac OS X. If you have Windows, I recommend dual-booting Ubuntu, or using VirtualBox or VMWare.

3) The CLTK does not distribute the PHI or TLG disks. Those you must obtain yourself. As in the docs you'll, you specify the path to these: `corpus_importer.import_corpus('tlg', '~/Documents/corpora/TLG_E/')` or `corpus_importer.import_corpus('phi7', '~/Documents/corpora/PHI7/')`.

If you need Greek files, take a look at the free Perseus corpus available for download; for Latin, try the Latin Library or Perseus corpora. Find these with `corpus_importer.list_corpora`.

May I ask, what is it you are trying to do? If you have more questions, use the main repo to ask.

**Comment by m-ramesh** [comment]
Hi, I cannot find the path to PHI7. I could find TLG. I assume PHI7 must be in the same folder as TLG. 

I am trying to use the CLTK to work on my own corpora. I have succeeded to an extent in importing these into CLTK, but I am still trying to use the tools on them. 

Would CLTK work well on Linux?

**Comment by kylepjohnson** [comment]
> Would CLTK work well on Linux?

Yes, it works great on Linux. I use Ubuntu sometimes. The CLTK is not supported on Microsoft Windows.

If you have correctly imported the PHI7, then you will find it in `~/cltk_data/greek/text/` or `~/cltk_data/latin/text/`, depending on how you imported it.

If you are getting errors, please copy-paste the entirety of the terminal text, both your commands and the errors.

Again, if you need more help, we are happy to help you with a new ticket at: https://github.com/cltk/cltk/issues
